#
# Copyright 2022 TikTok Pte. Ltd.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.
#

#use_frameworks!

platform :ios, '11.0'

target 'TikTokLoginDemo' do
  pod 'TikTokOpenSDKCore', :path => '../'
  pod 'TikTokOpenAuthSDK', :path => '../', :testspecs => ['UnitTests']

end
