#
# Copyright 2022 TikTok Pte. Ltd.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.
#

#use_frameworks!

platform :ios, '11.0'

target 'TikTokShareDemo' do
  pod 'QBImagePickerController'
  pod 'TikTokOpenSDKCore', :path => '../' 
  pod 'TikTokOpenShareSDK', :path => '../', :testspecs => ['UnitTests']

end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
  end
 end
end
